# name: PHPStan

# on:
#   push:
#     branches: [ master, develop ]
#   pull_request:
#     branches: [ master, develop ]

# jobs:
  phpstan-linter:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v2
      - name: Run php check code with reviewdog
        uses: GeneaLabs/action-reviewdog-phpstan
