# This is a basic workflow to help you get started with Actions

name: thunderscan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
          
 - name: DefenseCode ThunderScan Action
 uses: defensecode/thunderscan-action@v1.0

